source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import register_view, RegisterView, UserDetailView
from webapp.views import UserList

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('user_list/', UserList.as_view(), name='list')
]

source/todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import TaskIndexView, TaskView, TaskDeleteView, TaskUpdateView, \
    ProjectIndexView, ProjectView, ProjectCreateView, ProjectTaskCreateView, ProjectDeleteView, \
    ProjectUpdateView, AddUserProject

app_name = 'webapp'

urlpatterns = [
    path('tasks', TaskIndexView.as_view(), name='index'),
    path('task/<int:pk>/', TaskView.as_view(), name='view'),
    path('task/<int:pk>/delete/', TaskDeleteView.as_view(), name='delete'),
    path('task/<int:pk>/update/', TaskUpdateView.as_view(), name='update'),
    path('', ProjectIndexView.as_view(), name='project_index'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project_view'),
    path('project/add', ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/task/add/', ProjectTaskCreateView.as_view(), name='create_task_project'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<int:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/add_user/', AddUserProject.as_view(), name='add_user'),
]

source/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user: AbstractUser = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE,
                                verbose_name='Пользователь')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    github = models.CharField(max_length=500, verbose_name='Ссылка на GitHub', blank=True)
    more = models.TextField(verbose_name='О себе', blank=True)

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/accounts/forms.py
from django.conf import settings
from django.contrib.auth.models import User, AbstractUser
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django import forms
from django.core.exceptions import ValidationError

from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(label='Email', required=True)

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2',
                  'first_name', 'last_name', 'email']
        field_classes = {'username': UsernameField}

    def save(self, commit=True):
        user = super().save(commit=commit)
        Profile.objects.create(user=user)
        return user

    def clean(self):
        cleaned_data = super().clean()
        errors = []
        email = cleaned_data.get('email')
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        if not first_name:
            if not last_name:
                errors.append(ValidationError('Заполните хотя бы одно из двух полей!'))
        if not email:
            errors.append(ValidationError('Введите Email'))
        if errors:
            raise ValidationError(errors)
        return cleaned_data

source/accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.urls import reverse
from django.views.generic import CreateView, DetailView

from .forms import MyUserCreationForm


def login_view(request):
    context = {}

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            context['has_error'] = True
    return render(request, 'registration/login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:index')


def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = MyUserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('webapp:index')
    else:
        form = MyUserCreationForm()
    return render(request, 'user_create.html', context={'form': form})


class RegisterView(CreateView):
    model = User
    template_name = 'user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url


class UserDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'

source/accounts/templates/user_create.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <h1>Регистрация</h1>
    {% include 'partial/form.html' with form_method='post' button_text="Зарегистрироваться" %}
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}Пользователь{% endblock %}

{% block menu %}
    <li class="nav-item active">
        <a class="nav-link" href="">Редактировать</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="">Смена пароля</a>
    </li>
{% endblock %}

{% block content %}
    <h2 id="center" class="my-4">Личная страница пользователя<br/> {{ user_obj.get_full_name|default:user_obj.username }}</h2>
    <div class="person">
    {% if user_obj.profile.avatar %}
        <img class="avatar mb-4" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">
    {% endif %}
    <div class="person-text">
    <h4 class="mb-2">Имя пользователя: <span id="link" class="">{{ user_obj.username }}</span></h4>
    {% if user_obj.first_name %}
        <h4>Имя: <span id="link" class="">{{ user_obj.first_name }}</span></h4>
    {% endif %}
    {% if user_obj.last_name %}
        <h4>Фамилия: <span id="link" class="">{{ user_obj.last_name }}</span></h4>
    {% endif %}
    {% if user_obj.profile.github %}
    <h4>Профиль на GitHub: <a id="link" href="{{ user_obj.profile.github }}">{{ user_obj.profile.github }}</a></h4>
    {% endif %}
    {% if user_obj.profile.more %}
    <h4>О себе: <span id="link" class="">{{ user_obj.profile.more }}</span></h4>
    {% endif %}
    </div>
    </div>
    <h2 class="text-center clear">Проекты пользователя:</h2>
    {% include 'partial/article_list.html' with projects=user_obj.projects.all %}
{% endblock %}

source/accounts/templates/user_list.html
{% extends 'base.html' %}

{% block title %}Список пользователей{% endblock %}


{% block content %}
    <div class="row">
    {% for user in users %}
        <div class="card mx-4 my-5" style="width: 18rem;">
        {% if user.profile.avatar %}
        <img class="avatar" src="{{ user.profile.avatar.url }}" width="250" height="250" alt="user picture">
        {% endif %}
          <div class="card-body">
            <h3 class="card-title">{{ user.username }}</h3>
            <a href="{% url 'accounts:detail' user.pk %}" class="btn btn-lg btn-primary">Подробнее</a>
          </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}