source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import register_view, RegisterView, UserDetailView
from webapp.views import UserList

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('user_list/', UserList.as_view(), name='list')
]

source/todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import TaskIndexView, TaskView, TaskDeleteView, TaskUpdateView, \
    ProjectIndexView, ProjectView, ProjectCreateView, ProjectTaskCreateView, ProjectDeleteView, \
    ProjectUpdateView, AddUserProject

app_name = 'webapp'

urlpatterns = [
    path('tasks', TaskIndexView.as_view(), name='index'),
    path('task/<int:pk>/', TaskView.as_view(), name='view'),
    path('task/<int:pk>/delete/', TaskDeleteView.as_view(), name='delete'),
    path('task/<int:pk>/update/', TaskUpdateView.as_view(), name='update'),
    path('', ProjectIndexView.as_view(), name='project_index'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project_view'),
    path('project/add', ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/task/add/', ProjectTaskCreateView.as_view(), name='create_task_project'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<int:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/add_user/', AddUserProject.as_view(), name='add_user'),
]

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Status(models.Model):
    name = models.CharField(max_length=30, null=False, blank=False, verbose_name='Статус')

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

    def __str__(self):
        return f'{self.name}'


class Type(models.Model):
    name = models.CharField(max_length=40, null=False, blank=False, verbose_name='Тип задачи')

    class Meta:
        verbose_name = 'Тип задачи'
        verbose_name_plural = 'Типы задач'

    def __str__(self):
        return f'{self.name}'


class Task(models.Model):
    summary = models.CharField(max_length=200, null=False, blank=False, verbose_name='Краткое описание')
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Полное описание')
    status = models.ForeignKey('webapp.Status', related_name='statuses', on_delete=models.PROTECT,
                               verbose_name='Статус', default='Новый')
    type = models.ManyToManyField('webapp.Type', related_name='types', blank=True,
                                  verbose_name='Тип задачи', default='Задача')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateField(auto_now=True, verbose_name='Дата обновления')
    project = models.ForeignKey('webapp.Project', related_name='tasks_project', on_delete=models.PROTECT,
                               verbose_name='Проект')

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    def __str__(self):
        return f'{self.pk} {self.summary}'


class Project(models.Model):
    start_date = models.DateField(verbose_name='Дата начала')
    end_date = models.DateField(verbose_name='Дата окончания', null=True, blank=True)
    name = models.CharField(max_length=200, null=False, blank=False, verbose_name='Название')
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Описание')
    user = models.ManyToManyField(User, related_name='projects', blank=True, verbose_name='Пользователь')

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def __str__(self):
        return f'{self.name}'

source/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Task, Status, Type, Project

BROWSER_DATETIME_FORMAT = '%Y-%m-%dT%H:%M'


def at_least_10(string):
    if len(string) < 10:
        raise ValidationError('Слишком коротко! Минимум 10 символов.')


def at_least_50(string):
    if len(string) < 50:
        raise ValidationError('Слишком коротко! Минимум 50 символов.')


class TaskForm(forms.ModelForm):
    summary = forms.CharField(validators=(at_least_10,), label='Короткое описание')
    description = forms.CharField(validators=(at_least_50,), required=False, widget=forms.Textarea,
                                  label='Подробное описание')

    class Meta:
        model = Task
        exclude = ['created_at', 'updated_at']
        widgets = {
            'type': forms.CheckboxSelectMultiple,
        }


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        widgets = {
            'description': forms.Textarea,
        }
        exclude = []


class ProjectTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ['project']


class UserAddForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['user']
        widgets = {
            'user': forms.CheckboxSelectMultiple
        }

source/webapp/views/project_viwes.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode
from webapp.models import Project, Task
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from webapp.forms import SimpleSearchForm, ProjectForm, TaskForm, ProjectTaskForm


class ProjectIndexView(LoginRequiredMixin, ListView):
    template_name = 'project/index.html'
    context_object_name = 'projects'
    model = Project
    ordering = ['start_date']

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(name__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class ProjectView(LoginRequiredMixin, DetailView):
    template_name = 'project/project_view.html'
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = User.objects.all()
        user = self.request.user
        object = self.get_object()
        
        return context


class ProjectCreateView(UserPassesTestMixin, CreateView):
    model = Project
    form_class = ProjectForm
    template_name = 'project/project_create.html'

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})

    def test_func(self):
        manager = User.objects.get(username='manager')
        return self.request.user == manager


class ProjectTaskCreateView(PermissionRequiredMixin, CreateView):
    model = Task
    template_name = 'project/task_in_project_create.html'
    form_class = ProjectTaskForm
    permission_denied_message = 'Отказано в доступе'
    permission_required = 'webapp.add_task'

    def has_permission(self):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        return super().has_permission() and self.request.user in project.user.all()

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        task = form.save(commit=False)
        task.project = project
        task.save()
        form.save_m2m()
        return redirect('webapp:project_view', pk=project.pk)


class ProjectDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'project/project_delete.html'
    model = Project
    success_url = reverse_lazy('webapp:project_index')
    permission_denied_message = 'Отказано в доступе'

    def test_func(self):
        manager = User.objects.get(username='manager')
        return self.request.user == manager


class ProjectUpdateView(UserPassesTestMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'project/project_update.html'
    permission_denied_message = 'Отказано в доступе'

    def test_func(self):
        manager = User.objects.get(username='manager')
        return self.request.user == manager

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})

source/webapp/views/task_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode
from webapp.models import Task, Project
from django.views.generic import TemplateView, FormView, ListView, DeleteView, UpdateView
from webapp.forms import TaskForm, SimpleSearchForm


class TaskIndexView(LoginRequiredMixin, ListView):
    template_name = 'task/index.html'
    context_object_name = 'tasks'
    model = Task
    ordering = ['pk']
    paginate_by = 6

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class TaskView(LoginRequiredMixin, TemplateView):
    template_name = 'task/task_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        task = get_object_or_404(Task, pk=pk)
        context['task'] = task
        return context


class TaskDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'task/task_delete.html'
    model = Task
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_task'

    def has_permission(self):
        task = self.get_object()
        return super().has_permission() and self.request.user in task.project.user.all()


class TaskUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'task/task_update.html'
    form_class = TaskForm
    model = Task
    permission_required = 'webapp.change_task'

    def get_success_url(self):
        return reverse('webapp:view', kwargs={'pk': self.object.pk})

    def has_permission(self):
        task = self.get_object()
        return super().has_permission() and self.request.user in task.project.user.all()

source/webapp/views/user_views.py
from django.contrib.auth.mixins import UserPassesTestMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect
from webapp.models import Project
from django.views.generic import UpdateView, ListView
from webapp.forms import UserAddForm


class AddUserProject(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'user/add_user.html'
    form_class = UserAddForm
    permission_denied_message = 'Отказано в доступе'
    permission_required = ('webapp.add_task',)
    # удаление юзера из списка чекбоксов по сути и есть удаление

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        form_kwargs = self.get_form_kwargs().get('data')
        form.save(commit=False)
        project.user.set(form_kwargs.get('user'))
        project.user.add(self.request.user)
        project.save()
        form.save_m2m()
        return redirect('webapp:project_view', pk=project.pk)

    def has_permission(self):
        return Project.objects.filter(user=self.request.user, pk=self.get_object().pk) and super().has_permission()


class UserList(PermissionRequiredMixin, ListView):
    model = User
    template_name = "user_list.html"
    queryset = User.objects.all()
    context_object_name = 'users'
    permission_required = 'accounts.view_user'

    def has_permission(self):
        return self.queryset

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}My Site{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar  navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'webapp:index' %}">TaskTracker</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'webapp:project_index' %}">На главную <span class="sr-only">(current)</span></a>
      </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'webapp:index' %}">Список всех задач</a>
      </li>
    {% if perms.auth.view_user %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:list' %}">Список пользователей</a>
    </li>
    {% endif %}
    {% if user.is_authenticated %}
        {% if perms.webapp.add_project %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'webapp:project_create'%}">Добавить проект</a>
            </li>
        {% endif %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:logout'%}?next={{ request.get_full_path }}">Выход</a>
      </li>
    {% else %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:login'%}?next={{ request.get_full_path }}">Вход</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:create'%}?next={{ request.get_full_path }}">Зарегестрироваться</a>
        </li>
    {% endif %}
        {% block menu %}{% endblock %}
    </ul>

  {% if user.is_authenticated %}
<form class="text-center" action="" method="GET">
    <label class="mx-2" id="label-search" for="{{ form.search.id_for_label }}">{{ form.search.label }}:</label>
    {{ form.search }}
    <input type="submit" value="Искать">
    {% for error in form.search.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
</form>
  {% endif %}
  </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>




<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
</body>
</html>